name: printer_sdk
description: Card printer SDK using R600 DLL
version: 1.0.0
#repository: 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  image: ^4.1.3

dev_dependencies:
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  test: ^1.24.9